name: Update recent track

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  update-recent-track:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        ref: gh-pages  # GitHub Pages用のブランチを指定

    - name: Set up Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and save recent track
      env:
        LASTFM_USER: ${{ secrets.LASTFM_USER }}
        API_KEY: ${{ secrets.API_KEY }}
      run: python scripts/request_and_save.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add recent_track.json
        git commit -m "Update recent track JSON"
        git push origin gh-pages
